// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/storage/entities/chat_message_entity.dart';
import 'core/storage/entities/contact_entity.dart';
import 'core/storage/entities/peer_entity.dart';
import 'core/storage/entities/tx_entity.dart';
import 'core/storage/entities/wallet_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1010061680843989750),
    name: 'PeerEntity',
    lastPropertyId: const obx_int.IdUid(5, 3475277421112028883),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7766543738734825291),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4740816107799956041),
        name: 'peerId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 7726032603119105699),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4598540245019741039),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1159459165212216066),
        name: 'trusted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3475277421112028883),
        name: 'lastSeen',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7311780424249181613),
    name: 'TxEntity',
    lastPropertyId: const obx_int.IdUid(10, 8935240952171975496),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6547542815416161554),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2099635702311067724),
        name: 'txId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 7666051317204458768),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 542374146466746261),
        name: 'from',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6726465179525280025),
        name: 'to',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8283707400001610370),
        name: 'amount',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2041337083914251737),
        name: 'timestamp',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4593828079496164321),
        name: 'signature',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8455324406619405932),
        name: 'nonce',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5899902125612051566),
        name: 'senderPublicKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8935240952171975496),
        name: 'parents',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 824099985797806823),
    name: 'WalletEntity',
    lastPropertyId: const obx_int.IdUid(4, 6503544043971122984),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2856720639112325242),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3204598887602104535),
        name: 'address',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 7646839850102533557),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7441841218607455296),
        name: 'publicKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6503544043971122984),
        name: 'balance',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5335436094303860318),
    name: 'ChatMessageEntity',
    lastPropertyId: const obx_int.IdUid(4, 2524978173224783778),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6630709663708312276),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6419994114331416214),
        name: 'fromId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4714901006043643441),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2524978173224783778),
        name: 'timestamp',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1686028110842712508),
    name: 'ContactEntity',
    lastPropertyId: const obx_int.IdUid(3, 2866140667726920890),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3924980358639477169),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6552662445754621125),
        name: 'publicKey',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 7934949130102768033),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2866140667726920890),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 1686028110842712508),
    lastIndexId: const obx_int.IdUid(4, 7934949130102768033),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    PeerEntity: obx_int.EntityDefinition<PeerEntity>(
      model: _entities[0],
      toOneRelations: (PeerEntity object) => [],
      toManyRelations: (PeerEntity object) => {},
      getId: (PeerEntity object) => object.id,
      setId: (PeerEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PeerEntity object, fb.Builder fbb) {
        final peerIdOffset = fbb.writeString(object.peerId);
        final addressOffset = fbb.writeString(object.address);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, peerIdOffset);
        fbb.addOffset(2, addressOffset);
        fbb.addBool(3, object.trusted);
        fbb.addInt64(4, object.lastSeen);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final peerIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final trustedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final lastSeenParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = PeerEntity(
          id: idParam,
          peerId: peerIdParam,
          address: addressParam,
          trusted: trustedParam,
          lastSeen: lastSeenParam,
        );

        return object;
      },
    ),
    TxEntity: obx_int.EntityDefinition<TxEntity>(
      model: _entities[1],
      toOneRelations: (TxEntity object) => [],
      toManyRelations: (TxEntity object) => {},
      getId: (TxEntity object) => object.id,
      setId: (TxEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TxEntity object, fb.Builder fbb) {
        final txIdOffset = fbb.writeString(object.txId);
        final fromOffset = fbb.writeString(object.from);
        final toOffset = fbb.writeString(object.to);
        final amountOffset = fbb.writeString(object.amount);
        final signatureOffset = fbb.writeString(object.signature);
        final senderPublicKeyOffset = fbb.writeString(object.senderPublicKey);
        final parentsOffset = fbb.writeString(object.parents);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, txIdOffset);
        fbb.addOffset(2, fromOffset);
        fbb.addOffset(3, toOffset);
        fbb.addOffset(4, amountOffset);
        fbb.addInt64(5, object.timestamp);
        fbb.addOffset(6, signatureOffset);
        fbb.addInt64(7, object.nonce);
        fbb.addOffset(8, senderPublicKeyOffset);
        fbb.addOffset(9, parentsOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final txIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final fromParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final toParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final amountParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final timestampParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final signatureParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final nonceParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final senderPublicKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final parentsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final object = TxEntity(
          id: idParam,
          txId: txIdParam,
          from: fromParam,
          to: toParam,
          amount: amountParam,
          timestamp: timestampParam,
          signature: signatureParam,
          nonce: nonceParam,
          senderPublicKey: senderPublicKeyParam,
          parents: parentsParam,
        );

        return object;
      },
    ),
    WalletEntity: obx_int.EntityDefinition<WalletEntity>(
      model: _entities[2],
      toOneRelations: (WalletEntity object) => [],
      toManyRelations: (WalletEntity object) => {},
      getId: (WalletEntity object) => object.id,
      setId: (WalletEntity object, int id) {
        object.id = id;
      },
      objectToFB: (WalletEntity object, fb.Builder fbb) {
        final addressOffset = fbb.writeString(object.address);
        final publicKeyOffset = fbb.writeString(object.publicKey);
        final balanceOffset = fbb.writeString(object.balance);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, addressOffset);
        fbb.addOffset(2, publicKeyOffset);
        fbb.addOffset(3, balanceOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final publicKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final balanceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = WalletEntity(
          id: idParam,
          address: addressParam,
          publicKey: publicKeyParam,
          balance: balanceParam,
        );

        return object;
      },
    ),
    ChatMessageEntity: obx_int.EntityDefinition<ChatMessageEntity>(
      model: _entities[3],
      toOneRelations: (ChatMessageEntity object) => [],
      toManyRelations: (ChatMessageEntity object) => {},
      getId: (ChatMessageEntity object) => object.id,
      setId: (ChatMessageEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ChatMessageEntity object, fb.Builder fbb) {
        final fromIdOffset = fbb.writeString(object.fromId);
        final textOffset = fbb.writeString(object.text);
        final timestampOffset = fbb.writeString(object.timestamp);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, fromIdOffset);
        fbb.addOffset(2, textOffset);
        fbb.addOffset(3, timestampOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final fromIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final timestampParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = ChatMessageEntity(
          id: idParam,
          fromId: fromIdParam,
          text: textParam,
          timestamp: timestampParam,
        );

        return object;
      },
    ),
    ContactEntity: obx_int.EntityDefinition<ContactEntity>(
      model: _entities[4],
      toOneRelations: (ContactEntity object) => [],
      toManyRelations: (ContactEntity object) => {},
      getId: (ContactEntity object) => object.id,
      setId: (ContactEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ContactEntity object, fb.Builder fbb) {
        final publicKeyOffset = fbb.writeString(object.publicKey);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, publicKeyOffset);
        fbb.addOffset(2, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final publicKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = ContactEntity(
          id: idParam,
          publicKey: publicKeyParam,
          name: nameParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [PeerEntity] entity fields to define ObjectBox queries.
class PeerEntity_ {
  /// See [PeerEntity.id].
  static final id = obx.QueryIntegerProperty<PeerEntity>(
    _entities[0].properties[0],
  );

  /// See [PeerEntity.peerId].
  static final peerId = obx.QueryStringProperty<PeerEntity>(
    _entities[0].properties[1],
  );

  /// See [PeerEntity.address].
  static final address = obx.QueryStringProperty<PeerEntity>(
    _entities[0].properties[2],
  );

  /// See [PeerEntity.trusted].
  static final trusted = obx.QueryBooleanProperty<PeerEntity>(
    _entities[0].properties[3],
  );

  /// See [PeerEntity.lastSeen].
  static final lastSeen = obx.QueryIntegerProperty<PeerEntity>(
    _entities[0].properties[4],
  );
}

/// [TxEntity] entity fields to define ObjectBox queries.
class TxEntity_ {
  /// See [TxEntity.id].
  static final id = obx.QueryIntegerProperty<TxEntity>(
    _entities[1].properties[0],
  );

  /// See [TxEntity.txId].
  static final txId = obx.QueryStringProperty<TxEntity>(
    _entities[1].properties[1],
  );

  /// See [TxEntity.from].
  static final from = obx.QueryStringProperty<TxEntity>(
    _entities[1].properties[2],
  );

  /// See [TxEntity.to].
  static final to = obx.QueryStringProperty<TxEntity>(
    _entities[1].properties[3],
  );

  /// See [TxEntity.amount].
  static final amount = obx.QueryStringProperty<TxEntity>(
    _entities[1].properties[4],
  );

  /// See [TxEntity.timestamp].
  static final timestamp = obx.QueryIntegerProperty<TxEntity>(
    _entities[1].properties[5],
  );

  /// See [TxEntity.signature].
  static final signature = obx.QueryStringProperty<TxEntity>(
    _entities[1].properties[6],
  );

  /// See [TxEntity.nonce].
  static final nonce = obx.QueryIntegerProperty<TxEntity>(
    _entities[1].properties[7],
  );

  /// See [TxEntity.senderPublicKey].
  static final senderPublicKey = obx.QueryStringProperty<TxEntity>(
    _entities[1].properties[8],
  );

  /// See [TxEntity.parents].
  static final parents = obx.QueryStringProperty<TxEntity>(
    _entities[1].properties[9],
  );
}

/// [WalletEntity] entity fields to define ObjectBox queries.
class WalletEntity_ {
  /// See [WalletEntity.id].
  static final id = obx.QueryIntegerProperty<WalletEntity>(
    _entities[2].properties[0],
  );

  /// See [WalletEntity.address].
  static final address = obx.QueryStringProperty<WalletEntity>(
    _entities[2].properties[1],
  );

  /// See [WalletEntity.publicKey].
  static final publicKey = obx.QueryStringProperty<WalletEntity>(
    _entities[2].properties[2],
  );

  /// See [WalletEntity.balance].
  static final balance = obx.QueryStringProperty<WalletEntity>(
    _entities[2].properties[3],
  );
}

/// [ChatMessageEntity] entity fields to define ObjectBox queries.
class ChatMessageEntity_ {
  /// See [ChatMessageEntity.id].
  static final id = obx.QueryIntegerProperty<ChatMessageEntity>(
    _entities[3].properties[0],
  );

  /// See [ChatMessageEntity.fromId].
  static final fromId = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[3].properties[1],
  );

  /// See [ChatMessageEntity.text].
  static final text = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[3].properties[2],
  );

  /// See [ChatMessageEntity.timestamp].
  static final timestamp = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[3].properties[3],
  );
}

/// [ContactEntity] entity fields to define ObjectBox queries.
class ContactEntity_ {
  /// See [ContactEntity.id].
  static final id = obx.QueryIntegerProperty<ContactEntity>(
    _entities[4].properties[0],
  );

  /// See [ContactEntity.publicKey].
  static final publicKey = obx.QueryStringProperty<ContactEntity>(
    _entities[4].properties[1],
  );

  /// See [ContactEntity.name].
  static final name = obx.QueryStringProperty<ContactEntity>(
    _entities[4].properties[2],
  );
}
