create table if not exists public.outcome_positions (
  id bigint generated by default as identity primary key,
  position_key text not null unique,
  event_id text not null references public.prediction_events(id) on delete cascade,
  outcome text not null,
  holder_address text not null,
  shares text not null default '0',
  shares_claimed text not null default '0'
);

create index if not exists idx_outcome_positions_event on public.outcome_positions(event_id);
create index if not exists idx_outcome_positions_holder on public.outcome_positions(holder_address);

alter table public.outcome_positions enable row level security;

create policy "outcome_positions_select_all"
  on public.outcome_positions for select
  to authenticated
  using (true);

create policy "outcome_positions_insert_admin"
  on public.outcome_positions for insert
  to authenticated
  with check (exists (select 1 from public.profiles p where p.auth_uid = auth.uid() and p.is_admin = true));

create policy "outcome_positions_update_admin"
  on public.outcome_positions for update
  to authenticated
  using (exists (select 1 from public.profiles p where p.auth_uid = auth.uid() and p.is_admin = true))
  with check (exists (select 1 from public.profiles p where p.auth_uid = auth.uid() and p.is_admin = true));

alter publication supabase_realtime add table public.outcome_positions;
