apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: doro-signaling
spec:
  template:
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/doro-signaling
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
